id: D133FA7AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:53:48+00:00'
last_modified: '2022-05-26T08:06:34.170149+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    503e:
      image_group_id: I1PD95858
      title: ཡེ་ཤེས་དབང་ཕྱུག་མའི་སྒྲུབ་ཐབས།
      total_pages: 2043
      order: 13
      base_file: 503e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
