id: P0BE4E8C0
initial_creation_type: ocr
source_metadata:
  volumes:
    9475ca8a68354ce4ab0d7eca91996444:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: ཡེ་ཤེས་དབང་ཕྱུག་མའི་སྒྲུབ་ཐབས།
      total_pages: 2043
      volume_number: 13
